export const AUDITOR_REQUEST_GET = "AUDITOR_REQUEST_GET";
export const AUDITOR_SUCCESS_GET = "AUDITOR_SUCCESS_GET";
export const AUDITOR_GET_FAIL = "AUDITOR_GET_FAIL";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const CATEGORY_REQUEST_GET= "CATEGORY_REQUEST_GET";
export const CATEGORY_SUCCESS_GET= "CATEGORY_SUCCESS_GET";
export const CATEGORY_GET_FAIL= "CATEGORY_GET_FAIL";

export const CATEGORY_REQUEST_EDIT= "CATEGORY_REQUEST_EDIT";
export const CATEGORY_SUCCESS_EDIT= "CATEGORY_SUCCESS_EDIT";
export const CATEGORY_EDIT_FAIL= "CATEGORY_EDIT_FAIL";

export const CATEGORY_DELETE_REQUEST= "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS= "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL= "CATEGORY_DELETE_FAIL";

export const STATE_REQUEST_GET= "STATE_REQUEST_GET";
export const STATE_SUCCESS_GET= "STATE_SUCCESS_GET";
export const STATE_GET_FAIL= "STATE_GET_FAIL";

export const USER_REQUEST_GET= "USER_REQUEST_GET";
export const USER_SUCCESS_GET= "USER_SUCCESS_GET";
export const USER_GET_FAIL= "USER_GET_FAIL";

export const NOTFICATION_CREATE_REQUEST = "NOTFICATION_CREATE_REQUEST";
export const NOTFICATION_CREATE_SUCCESS = "NOTFICATION_CREATE_SUCCESS";
export const NOTFICATION_CREATE_FAIL = "NOTFICATION_CREATE_FAIL";

export const NOTFICATION_REQUEST_GET = "NOTFICATION_REQUEST_GET";
export const NOTFICATION_SUCCESS_GET = "NOTFICATION_SUCCESS_GET";
export const NOTFICATION_GET_FAIL = "NOTFICATION_GET_FAIL";    

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_REQUEST_EDIT= "USER_REQUEST_EDIT";
export const USER_SUCCESS_EDIT= "USER_SUCCESS_EDIT";
export const USER_EDIT_FAIL= "USER_EDIT_FAIL";

export const CHECKLIST_CREATE_REQUEST= "CHECKLIST_CREATE_REQUEST";
export const CHECKLIST_CREATE_SUCCESS= "CHECKLIST_CREATE_SUCCESS";
export const CHECKLIST_CREATE_FAIL= "CHECKLIST_CREATE_FAIL";

export const CHECKLIST_REQUEST_GET= "CHECKLIST_REQUEST_GET";
export const CHECKLIST_SUCCESS_GET= "CHECKLIST_SUCCESS_GET";
export const CHECKLIST_GET_FAIL= "CHECKLIST_GET_FAIL";

export const CHECKLIST_REQUEST_UPDATE_BYID= "CHECKLIST_REQUEST_UPDATE_BYID";
export const CHECKLIST_SUCCESS_UPDATE_BYID= "CHECKLIST_SUCCESS_UPDATE_BYID";
export const CHECKLIST_FAIL_UPDATE_BYID= "CHECKLIST_FAIL_UPDATE_BYID";

export const CHECKLIST_REQUEST_GET_CREATE= "CHECKLIST_REQUEST_GET_CREATE";
export const CHECKLIST_SUCCESS_GET_CREATE= "CHECKLIST_SUCCESS_GET_CREATE";
export const CHECKLIST_GET_FAIL_CREATE= "CHECKLIST_GET_FAIL_CREATE";

export const CHECKLIST_REQUEST_GET_BYID= "CHECKLIST_REQUEST_GET_BYID";
export const CHECKLIST_SUCCESS_GET_BYID= "CHECKLIST_SUCCESS_GET_BYID";
export const CHECKLIST_FAIL_GET_BYID= "CHECKLIST_FAIL_GET_BYID";    

export const CHECKLIST_REQUEST_GET_ALL= "CHECKLIST_REQUEST_GET_ALL";
export const CHECKLIST_SUCCESS_GET_ALL= "CHECKLIST_SUCCESS_GET_ALL";
export const CHECKLIST_GET_FAIL_ALL= "CHECKLIST_GET_FAIL_ALL";    

export const CHECKLIST_REQUEST_GET_APPROVE= "CHECKLIST_REQUEST_GET_APPROVE";
export const CHECKLIST_SUCCESS_GET_APPROVE= "CHECKLIST_SUCCESS_GET_APPROVE";
export const CHECKLIST_REQUEST_GET_APPROVE_FAIL= "CHECKLIST_REQUEST_GET_APPROVE_FAIL";    

export const CHECKLIST_REQUEST_ALL_FILTER= "CHECKLIST_REQUEST_ALL_FILTER";
export const CHECKLIST_SUCCESS_ALL_FILTER= "CHECKLIST_SUCCESS_ALL_FILTER";
export const CHECKLIST_ALL_FAIL_FILTER= "CHECKLIST_ALL_FAIL_FILTER";    

export const CHECKLIST_REQUEST_CREATE_FILTER= "CHECKLIST_REQUEST_CREATE_FILTER";
export const CHECKLIST_SUCCESS_CREATE_FILTER= "CHECKLIST_SUCCESS_CREATE_FILTER";
export const CHECKLIST_ALL_CREATE_FILTER= "CHECKLIST_ALL_CREATE_FILTER";    

export const CHECKLIST_REQUEST_All_COMPLIANCE= "CHECKLIST_REQUEST_All_COMPLIANCE";
export const CHECKLIST_SUCCESS_All_COMPLIANCE= "CHECKLIST_SUCCESS_All_COMPLIANCE";
export const CHECKLIST_FAIL_All_COMPLIANCE= "CHECKLIST_FAIL_All_COMPLIANCE";   

export const CHECKLIST_REQUEST_REJECT_FILTER= "CHECKLIST_REQUEST_REJECT_FILTER";
export const CHECKLIST_SUCCESS_REJECT_FILTER= "CHECKLIST_SUCCESS_REJECT_FILTER";
export const CHECKLIST_ALL_REJECT_FILTER= "CHECKLIST_ALL_REJECT_FILTER";

export const CHECKLIST_REQUEST_REJECT= "CHECKLIST_REQUEST_REJECT";
export const CHECKLIST_SUCCESS_REJECT= "CHECKLIST_SUCCESS_REJECT";
export const CHECKLIST_REQUEST_REJECT_FAIL= "CHECKLIST_REQUEST_REJECT_FAIL";   

export const CHECKLIST_REQUEST_GET_REJECT= "CHECKLIST_REQUEST_GET_REJECT";
export const CHECKLIST_SUCCESS_GET_REJECT= "CHECKLIST_SUCCESS_GET_REJECT";
export const CHECKLIST_GET_FAIL_REJECT= "CHECKLIST_GET_FAIL_REJECT"; 

export const AUDIT_REQUEST_All_DETAIL= "AUDIT_REQUEST_All_DETAIL";
export const AUDIT_SUCCESS_All_DETAIL= "AUDIT_SUCCESS_All_DETAIL";
export const AUDIT_FAIL_All_DETAIL= "AUDIT_FAIL_All_DETAIL";     

export const BRANCH_REQUEST_GET= "BRANCH_REQUEST_GET";
export const BRANCH_SUCCESS_GET= "BRANCH_SUCCESS_GET";
export const BRANCH_GET_FAIL= "BRANCH_GET_FAIL";

export const COMPANY_REQUEST_GET= "COMPANY_REQUEST_GET";
export const COMPANY_SUCCESS_GET= "COMPANY_SUCCESS_GET";
export const COMPANY_GET_FAIL= "COMPANY_GET_FAIL";

export const COMPLIANCE_REQUEST_GET= "COMPLIANCE_REQUEST_GET";
export const COMPLIANCE_SUCCESS_GET= "COMPLIANCE_SUCCESS_GET";
export const COMPLIANCE_GET_FAIL= "COMPLIANCE_GET_FAIL";

export const CHECKLIST_REQUEST_APPROVE_FILTER= "CHECKLIST_REQUEST_APPROVE_FILTER";
export const CHECKLIST_SUCCESS_APPROVE_FILTER= "CHECKLIST_SUCCESS_APPROVE_FILTER";
export const CHECKLIST_ALL_APPROVE_FILTER= "CHECKLIST_ALL_APPROVE_FILTER";

export const CHECKLIST_REQUEST_GET_APPROVE_PAGE= "CHECKLIST_REQUEST_GET_APPROVE_PAGE";
export const CHECKLIST_SUCCESS_GET_APPROVE_PAGE= "CHECKLIST_SUCCESS_GET_APPROVE_PAGE";
export const CHECKLIST_GET_FAIL_APPROVE_PAGE= "CHECKLIST_GET_FAIL_APPROVE_PAGE";

export const COMPLIANCE_REQUEST_APPROVE_FILTER= "COMPLIANCE_REQUEST_APPROVE_FILTER";
export const COMPLIANCE_SUCCESS_APPROVE_FILTER= "COMPLIANCE_SUCCESS_APPROVE_FILTER";
export const COMPLIANCE_APPROVE_FAIL_FILTER= "COMPLIANCE_APPROVE_FAIL_FILTER";

export const COMPLIANCE_SUCCESS_GET_ALL_FILTER= "COMPLIANCE_SUCCESS_GET_ALL_FILTER";
export const COMPLIANCE_REQUEST_GET_ALL_FILTER= "COMPLIANCE_REQUEST_GET_ALL_FILTER";
export const COMPLIANCE_GET_FAIL_ALL_FILTER= "COMPLIANCE_GET_FAIL_ALL_FILTER";

export const COMPLIANCE_REQUEST_REJECT_FILTER= "COMPLIANCE_REQUEST_REJECT_FILTER";
export const COMPLIANCE_SUCCESS_REJECT_FILTER= "COMPLIANCE_SUCCESS_REJECT_FILTER";
export const COMPLIANCE_REJECT_FAIL_FILTER= "COMPLIANCE_REJECT_FAIL_FILTER";

export const COMPLIANCE_REQUEST_GET_ALL= "COMPLIANCE_REQUEST_GET_ALL";
export const COMPLIANCE_SUCCESS_GET_ALL= "COMPLIANCE_SUCCESS_GET_ALL";
export const COMPLIANCE_GET_FAIL_ALL= "COMPLIANCE_GET_FAIL_ALL";

export const COMPLIANCE_REQUEST_GET_CREATE= "COMPLIANCE_REQUEST_GET_CREATE";
export const COMPLIANCE_SUCCESS_GET_CREATE= "COMPLIANCE_SUCCESS_GET_CREATE";
export const COMPLIANCE_GET_FAIL_CREATE= "COMPLIANCE_GET_FAIL_CREATE";


export const COMPLIANCE_REQUEST_GET_BYID= "COMPLIANCE_REQUEST_GET_BYID";
export const COMPLIANCE_SUCCESS_GET_BYID= "COMPLIANCE_SUCCESS_GET_BYID";
export const COMPLIANCE_FAIL_GET_BYID= "COMPLIANCE_FAIL_GET_BYID";

export const BRANCH_CREATE_REQUEST = "BRANCH_CREATE_REQUEST";
export const BRANCH_CREATE_SUCCESS = "BRANCH_CREATE_SUCCESS";
export const BRANCH_CREATE_FAIL = "BRANCH_CREATE_FAIL";

export const COMPANY_CREATE_REQUEST = "COMPANY_CREATE_REQUEST";
export const COMPANY_CREATE_SUCCESS = "COMPANY_CREATE_SUCCESS";
export const COMPANY_CREATE_FAIL = "COMPANY_CREATE_FAIL";

export const COMPLIANCE_CREATE_REQUEST = "COMPLIANCE_CREATE_REQUEST";
export const COMPLIANCE_CREATE_SUCCESS = "COMPLIANCE_CREATE_SUCCESS";
export const COMPLIANCE_CREATE_FAIL = "COMPLIANCE_CREATE_FAIL";

export const COMPLIANCE_REQUEST_UPDATE_BYID = "COMPLIANCE_REQUEST_UPDATE_BYID";
export const COMPLIANCE_SUCCESS_UPDATE_BYID = "COMPLIANCE_SUCCESS_UPDATE_BYID";
export const COMPLIANCE_FAIL_UPDATE_BYID = "COMPLIANCE_FAIL_UPDATE_BYID";

export const COMPLIANCE_REQUEST_GET_APPROVE = "COMPLIANCE_REQUEST_GET_APPROVE";
export const COMPLIANCE_SUCCESS_GET_APPROVE = "COMPLIANCE_SUCCESS_GET_APPROVE";
export const COMPLIANCE_REQUEST_GET_APPROVE_FAIL = "COMPLIANCE_REQUEST_GET_APPROVE_FAIL";

export const COMPLIANCE_REQUEST_GET_FILTER = "COMPLIANCE_REQUEST_GET_FILTER";
export const COMPLIANCE_SUCCESS_GET_FILTER = "COMPLIANCE_SUCCESS_GET_FILTER";
export const COMPLIANCE_GET_FAIL_FILTER = "COMPLIANCE_GET_FAIL_FILTER";

export const COMPLIANCE_REQUEST_GET_REJECT = "COMPLIANCE_REQUEST_GET_REJECT";
export const COMPLIANCE_SUCCESS_GET_REJECT = "COMPLIANCE_SUCCESS_GET_REJECT";
export const COMPLIANCE_REQUEST_GET_REJECT_FAIL = "COMPLIANCE_REQUEST_GET_REJECT_FAIL";

export const COMPLIANCE_REQUEST_REJECT = "COMPLIANCE_REQUEST_REJECT";
export const COMPLIANCE_SUCCESS_REJECT = "COMPLIANCE_SUCCESS_REJECT";
export const COMPLIANCE_REQUEST_REJECT_FAIL = "COMPLIANCE_REQUEST_REJECT_FAIL";

export const NAMERATE_CREATE_REQUEST = "NAMERATE_CREATE_REQUEST";
export const NAMERATE_CREATE_SUCCESS = "NAMERATE_CREATE_SUCCESS";
export const NAMERATE_CREATE_FAIL = "NAMERATE_CREATE_FAIL";

export const DOC_CREATE_REQUEST = "DOC_CREATE_REQUEST";
export const DOC_CREATE_SUCCESS = "DOC_CREATE_SUCCESS";
export const DOC_CREATE_FAIL = "DOC_CREATE_FAIL";